"""
Example C — Tools with function calling (a real agent)
======================================================

The reference used OpenAI's function-calling API. This is the same idea on free
Gemini via LangChain: you give the model TOOLS (plain Python functions), it
decides which to call and with what arguments, your code runs them and feeds the
results back, and it loops until it can answer. That loop IS the agent (Examples
A & B).

User Question
      │
      ▼
      LLM
      │
      ▼
Needs a tool?
      │
 ┌────┴─────┐
 │          │
Yes        No
 │          │
 ▼          ▼
Tool Call  Final Answer
 │
 ▼
Python Function
 │
 ▼
Tool Result
 │
 ▼
Back to LLM


Key LangChain pieces:
  - `@tool`                : marks a function as callable by the LLM; its
                             docstring + type hints become the tool schema.
  - `llm.bind_tools([...])`: tells the model which tools exist.
  - response `.tool_calls` : the model's requested calls (name, args, id).
  - `ToolMessage`          : how you hand a tool's result back to the model.

Run:
    ../1.KPI_Narrator/.venv/bin/python 3.function_calling_agent.py
"""

import json
import os
import sys
from pathlib import Path

from langchain_core.messages import HumanMessage, SystemMessage, ToolMessage
from langchain_core.tools import tool
from langchain_google_genai import ChatGoogleGenerativeAI

try:
    from dotenv import load_dotenv

    for _p in (Path(__file__).parent / ".env",
               Path(__file__).parent.parent / "1.KPI_Narrator" / ".env"):
        if _p.exists():
            load_dotenv(_p)
            break
except ImportError:
    pass

if not os.getenv("GOOGLE_API_KEY"):
    sys.exit("GOOGLE_API_KEY not set. Put it in ../1.KPI_Narrator/.env")


# ── TOOLS: plain Python functions the agent can call ────────────────────────
@tool
def get_kpi(metric_id: str) -> dict:
    """Get current and prior KPI value by metric ID like D-110 or D-150."""
    db = {
        "D-110": {"name": "SDK activations", "value": 12000, "prior": 24000},
        "D-150": {"name": "ARPU IDR", "value": 44000, "prior": 42000},
    }
    return db.get(metric_id, {"error": "not found"})


@tool
def rag_search(query: str) -> list:
    """Search internal QBR and ops documents for relevant snippets."""
    docs = [
        {"text": "SDK rollout paused in 2 regions", "source_id": "ops_w25"},
        {"text": "Q2 commitment: SDK funnel by August", "source_id": "qbr_q2"},
    ]
    words = query.lower().split()
    return [d for d in docs if any(w in d["text"].lower() for w in words)]


TOOLS = [get_kpi, rag_search]
TOOL_MAP = {t.name: t for t in TOOLS}

llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash-lite", temperature=0.2).bind_tools(TOOLS)


#@tool: Exposes a Python function as a callable tool, using its signature and docstring to describe it to the model.
#llm.bind_tools([...]): Registers the available tools with the model.
#response.tool_calls: Contains the structured tool requests generated by the model.
#ToolMessage: Sends each tool's output back to the model so it can continue reasoning or produce a final answer.


def _text(content) -> str:
    """Gemini may return content as a list of blocks (thinking + text). Join the
    text parts into a plain string."""
    if isinstance(content, str):
        return content.strip()
    parts = []
    for b in content:
        if isinstance(b, str):
            parts.append(b)
        elif isinstance(b, dict) and b.get("type") == "text":
            parts.append(b.get("text", ""))
    return "".join(parts).strip()


def run_agent(user_question: str, max_steps: int = 5) -> str:
    messages = [
        SystemMessage(content=(
            "You are Wise Albert's analysis agent. "
            "Use tools to gather evidence. Cite metric IDs and source_id. "
            "Never invent numbers."
        )),
        HumanMessage(content=user_question),
    ]

    for step in range(max_steps):
        ai = llm.invoke(messages)      # THINK — the model decides what to do
        messages.append(ai)
        print("ai: ", ai)

        # No tool call -> the model is done and this is the final answer.
        if not ai.tool_calls:
            return _text(ai.content)

        # ACT + OBSERVE — run each requested tool, feed the result back.
        for tc in ai.tool_calls:
            print(f"  [step {step}] ACT: {tc['name']}({tc['args']})")
            result = TOOL_MAP[tc["name"]].invoke(tc["args"])
            print(f"            OBSERVE: {result}")
            # add the tool result to the message history for the LLM
            messages.append(ToolMessage(
                content=json.dumps(result),
                tool_call_id=tc["id"],
            ))

    return "Max steps reached — incomplete."


def main() -> None:
    q = "Why did SDK activation drop? What did we promise about the funnel?"
    print("Q:", q)
    answer = run_agent(q)
    print("\nA:", answer)
    print(
        "\nThe agent chose which tools to call and in what order itself (watch the\n"
        "ACT/OBSERVE steps above) — there is no fixed pipeline. Run it again and\n"
        "the tool sequence may differ."
    )


if __name__ == "__main__":
    main()
